### ISSUE TITLE
My bots

### ISSUE THREAD

**Issue by EQuimper** [amandeepmittal/awesome-twitter-bots#3]
Repos: https://github.com/EQuimper/MyOwnChallenge-SuperHeroesTwitterBotCoding

Twitter Link: https://twitter.com/heroes_bot

Let me know if all that is okay.

**Comment by amandeepmittal** [comment]
Yes, it's great. You can create a PR for `README.md` file and add the name & links to your bot and repo there. Just follow the pattern for brevity.

**Comment by EQuimper** [comment]
Ok perfect thank you
